#fsxZ-storage-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-openzfs-pvc-saz
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-openzfs-sc-saz
  resources:
    requests:
      storage: 1200Gi
