#fsxZ-storage-class.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-openzfs-sc-saz
provisioner: fsx.openzfs.csi.aws.com
parameters:
  ResourceType: "filesystem" 
  DeploymentType: '"SINGLE_AZ_1"' 
  ThroughputCapacity: '64' 
  SubnetIds: '["SUBNET_ID_1"]'  
  SkipFinalBackupOnDeletion: 'true' 
  OptionsOnDeletion: '["DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"]' 
  KmsKeyId: '"FSX_KEY"'    
  AutomaticBackupRetentionDays: '1'
  CopyTagsToBackups: 'false'
  CopyTagsToVolumes: 'false'
  DailyAutomaticBackupStartTime: '"00:00"'
  DiskIopsConfiguration: '{"Iops": 3600, "Mode": "USER_PROVISIONED"}'
  RootVolumeConfiguration: '{"CopyTagsToSnapshots": false, "DataCompressionType": "NONE", "NfsExports": [{"ClientConfigurations": [{"Clients": "*", "Options": ["rw","crossmnt"]}]}], "ReadOnly": false, "RecordSizeKiB": 128, "UserAndGroupQuotas": [{"Type": "USER", "Id": 1, "StorageCapacityQuotaGiB": 10}]}'
  WeeklyMaintenanceStartTime: '"7:09:00"'
  SecurityGroupIds: '["SECURITY_GROUP_ID"]'     
  Tags: '[{"Key": "OPENZFS", "Value": "OPENZFS"}]'
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - timeo=600
  