apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: mysql
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    command: ['/bin/sh','-c', "sleep 4320m"]
    imagePullPolicy: IfNotPresent
