# pod_performance_different_AZ.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-trident-nas-pv-claim-daz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: trident-csi
---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod-daz
spec:
  volumes:
    - name: task-trident-nas-pv-storage-daz
      persistentVolumeClaim:
        claimName: task-trident-nas-pv-claim-daz
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/trident-nas/"
          name: task-trident-nas-pv-storage-daz
  nodeSelector: # to make sure the pod stays in the different region
    topology.kubernetes.io/zone: us-west-2b
