kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-trident-nas-pv-claim-saz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: trident-csi
---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod-saz
spec:
  volumes:
    - name: task-trident-nas-pv-storage-saz
      persistentVolumeClaim:
        claimName: task-trident-nas-pv-claim-saz
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/trident-nas/"
          name: task-trident-nas-pv-storage-saz
  nodeSelector: # to make sure the pod stays in the same region
    topology.ebs.csi.aws.com/zone: us-west-2a
