apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: FSx-eks-cluster
  region: ap-southeast-2
vpc:
  id: vpc-id #replace with your vpcId
  clusterEndpoints:
    privateAccess: false
    publicAccess: true # Create the EKS control planes in the public subnets
  subnets:
    public: # Create the EKS control planes in the public subnets
      ap-southeast-2a: { id: public-subnet-1 } #replace with your subnetid
      ap-southeast-2b: { id: public-subnet-2 }
iam:
  withOIDC: true
addons:
  - name: vpc-cni # no version is specified so it deploys the default version
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest # auto discovers the latest available
managedNodeGroups:
  - name: ng-1-workers
    # Create the EKS Managed Node Groups in the private subnets
    subnets: [ 'private-subnet1', 'private-subnet2'] #replace with your subnetId
    labels: { role: workers }
    instanceType: c5.2xlarge
    desiredCapacity: 2
    ssh:
      enableSsm: true
    # iam:
    #   withAddonPolicies:
    #     ebs: true
    #     efs: true
cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
