kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backup-restore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: trident-csi  