AWSTemplateFormatVersion: 2010-09-09
Description: "Security Groups For FSX Lustre"

Parameters:
  SecurityGroupName: 
    Type: String
    Description: "FSx Lustre Security Group Name"
Resources:
  FSxLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      VpcId: myVpc
      GroupDescription: Security Group for FSx for Lustre Storage Access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 988
          ToPort: 988
          Description: Allow Lustre traffic between FSx for Lustre file servers
          #SourceSecurityGroupId: FSxLSecurityGroupID
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1021
          ToPort: 1023
          Description: Allows Lustre traffic between FSx for Lustre file servers
          #SourceSecurityGroupId: FSxLSecurityGroupID
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          Description: Allows Lustre traffic between FSx for Lustre file servers
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref FSxLSecurityGroup
